<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

In [1]:
import numpy as np

### 1.1 Let’s compare

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [4]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [5]:
print(py_real_names[0]) #indexing
print(py_super_names[0])
print(py_real_names[-3]) #reverse indexing

Natasha Romanoff
Black Widow
Natasha Romanoff


### 1.3 Accessing data from a dictionary

In [6]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

In [7]:
print(superhero_info["Natasha Romanoff"]) #Drawing Info from the dictionary

Black Widow


In [8]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [9]:
superhero_info.values()


dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [10]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

## 2 Lists vs. Arrays

### 2.1 Size

In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
print(np_array_2d)
print(np_array_2d.flatten()) #Collapsing the list

[['1' 'A']
 ['2' 'B']
 ['3' 'C']
 ['4' 'D']
 ['5' 'E']
 ['6' 'F']
 ['7' 'G']
 ['8' 'H']
 ['9' 'I']
 ['10' 'J']]
['1' 'A' '2' 'B' '3' 'C' '4' 'D' '5' 'E' '6' 'F' '7' 'G' '8' 'H' '9' 'I'
 '10' 'J']


In [12]:
len(py_list_2d) #count number of elements


10

In [13]:
np_array_2d.shape #Number of rows and columns

(10, 2)

### 2.2 Arrays are fussy about type

In [14]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [15]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [16]:
py_list + 10 #doesnt work --> the type is a string

TypeError: can only concatenate list (not "int") to list

In [17]:
np_array + 10 #Values

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [18]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [19]:
py_list_1 + py_list_2 #Combining the two lists together

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [20]:
np_array_1 + np_array_2 #Adds the value of the corrsesponding indexes together

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [21]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [22]:
py_list*2 #Doubles the list in terms of its count

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [23]:
np_array*2 #Doubles the values of the indexes in the lsit

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [24]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [25]:
py_list**2 

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [26]:
np_array**2 #Squaring the indexes

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [27]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [28]:
py_list == 3 #What is false? what is it telling me

False

In [29]:
py_list > 3

TypeError: '>' not supported between instances of 'list' and 'int'

In [30]:
np_array == 3 #asks if it equals to 3 to all the indexes

array([False, False,  True, False, False])

In [31]:
np_array > 3 #asks if is more than 3 to all the indexes

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [32]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [33]:
sum(py_list) 

15

In [34]:
max(py_list) #max() is supposed to give us the largest value

5

In [35]:
min(py_list) #min() is suposed to give us the lowest vallue

1

In [36]:
py_list.sum()

AttributeError: 'list' object has no attribute 'sum'

In [37]:
np_array.sum()

15

In [38]:
np_array.mean()

3.0

In [39]:
np_array.max()

5

In [40]:
np_array.min()

1

In [41]:
#Performing of arithmetics to our indexes and lists

## Exercise 1 :  Total recall?

1. Similarities
    1. They are able to compile our values together into a list to be shown as an output.
    2. We are able to index and find our values for both.

2. Differences
    1. Lists are values recognised as strings, however arrays are recognised as integers. 
    1. We are unable to perform arithimic functions on lists but we can on arrays. For example we are able to add corresponding indexes together between two lists but by inputing that same function into a string, it will compile both lists into one list.
    
3. Dictionaries give keys a value. It gives meaning an subsequently another value.


## Exercise 2 :  Index me

In [42]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'


a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [43]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()   
print(superhero_info['Tony Stark'])
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
print(superhero_info['Natasha Romanoff'])
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()
print(superhero_info['Stephen Strange'])

IRON MAN
BLACK WIDOW
DOCTOR STRANGE


## Exercise 4 :  How many ones

In [62]:
numbers = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61] 
import numpy
np_array = numpy.array(numbers)
x = np_array == 1
x.sum()


[9]
