<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [4]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
import numpy as np
np_array = np.array(py_list)
x=np_array
x[::2]

array(['a1', 'c3', 'e5', 'g7', 'i9'], dtype='<U3')

### 1.2 Subsetting by masking (Arrays only)

In [2]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)
np_array[my_mask]

[False False False  True  True  True  True  True  True  True]


array([ 4,  5,  6,  7,  8,  9, 10])

In [4]:
np_array[~(my_mask)] #NOT (>3)

array([1, 2, 3])

In [5]:
np_array[(my_mask) & (np_array < 8)] #AND function

array([4, 5, 6, 7])

In [8]:
np_array[(my_mask) | (np_array == 1)] #OR function

array([ 1,  4,  5,  6,  7,  8,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [15]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[3][1]
py_list_2d[:3]
py_list_2d[:3][0]

[1, 'A']

### 1.4 Indexing & Slicing 2D Arrays

In [27]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

np_array_2d[3]
print(np_array_2d[3, 0])
print(np_array_2d[3][0])
np_array_2d[:3, 0]
np_array_2d[:, 0]

4
4


array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [30]:
x=[1]*10
x               # I am lazy to type print()
                # Let Jupyter do the hard work.

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [35]:
x=[1]
x= x + [2]
x= x + [3]
x += [4]
x

[1, 2, 3, 4]

In [37]:
x=[1]
x+=[2,3,4]
x

[1, 2, 3, 4]

In [41]:
x=[1]
x=[2,3,4] + x #directional
x

[2, 3, 4, 1]

In [44]:
x=[1]
x.append(2)
x.append(3)
x.append(72)
x

[1, 2, 3, 72]

### 2.1 Tuples

In [47]:
a=(1,2,3)
print(a[0])

a[0]=-1

1


TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [51]:
x=[1,2,3]
y=x.copy()
y

[1, 2, 3]

## Exercise 1 :  Total recall?

1. Subsetting: *To select elements in a list*
1. Indexing: Selectively choosing and calling for specific elements in a list
1. Slicing: To selectively choose a range of elements in a list
1. Masking: To only allow true subets to be seen

## Exercise 2 :  Show me the ‘odd’ letters

In [55]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [84]:
np_array_2d[:, 0]
np_array_2d_int = np_array_2d[:,0].astype(int)
np_array_2d_rmd = np_array_2d_int % 2
np_array_2d_odd = np_array_2d_rmd==1
np_array_2d[np_array_2d_odd, 1]


array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')